<?php
return [
    'jakarta' => 'https://corona.jakarta.go.id/id',
    'jogjakarta' => 'https://corona.jogjaprov.go.id/',
    'jateng' => 'https://corona.jatengprov.go.id/',
    'jabar' =>  'https://pikobar.jabarprov.go.id/',
    'jatim' => 'https://infocovid19.jatimprov.go.id/',
    'banten' => 'https://www.bantenprov.go.id/covid-19',
    'bali' => 'https://www.diskes.baliprov.go.id/',
    'kaltim' => 'https://kaltimprov.go.id/',
    'kepri' => 'https://www.kepriprov.go.id/',
    'sultra' => 'http://www.sultraprov.go.id/',
    'sumut' => 'https://www.sumutprov.go.id/artikel/artikel',
    'kalbar' => 'https://dinkes.kalbarprov.go.id/covid-19/',
    'kalteng' => 'https://www.kalteng.go.id/home',
    'sulsel' => 'https://sulselprov.go.id/',
    'papua' => 'https://www.papua.go.id/',
    'riau' => 'https://www.riau.go.id/home/',
    'lampung' => 'https://lampungprov.go.id/',
    'kalsel' => 'http://www.kalselprov.go.id/',
    'sulut' => 'https://www.sulutprov.go.id/',
    'maluku' => 'https://malukuprov.go.id/',
    'aceh' => 'https://covid19.acehprov.go.id/',
    'sumbar' => 'https://corona.sumbarprov.go.id/',
    'jambi' => 'https://jambikota.go.id/new/',
    'sumsel' => 'https://sumselprov.go.id/',
    'bengkulu' => 'https://bengkuluprov.go.id/',
    'babel' => 'https://www.babelprov.go.id/',
    'ntb' => 'https://www.ntbprov.go.id/',
    'ntt' => 'http://nttprov.go.id/',
    'kaltara' => 'https://humas.kaltaraprov.go.id/',
    'sulteng' => 'https://www.sultengprov.go.id/',
    'gorontalo' => 'https://www.gorontaloprov.go.id/',
    'sulbar' => 'https://www.sulbarprov.go.id/',
    'malut' => 'https://www.sulbarprov.go.id/',
    'pabar' => 'https://papuabaratprov.go.id/'
]